name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/joke-client:0.1
        echo {{secrets.GHCR_TOKEN}} | docker login ghcr.io -u zoltaibalazs --password-stdin
        docker push ghcr.io/joke-client:0.1
